export const foodData = [
	{ char: '🍎', name: '苹果', keywords: ['苹果', '水果', '红'] },
	{ char: '🍐', name: '梨', keywords: ['梨', '水果'] },
	{ char: '🍊', name: '橙', keywords: ['橙', '水果', '柑橘'] },
	{ char: '🍋', name: '柠檬', keywords: ['柠檬', '酸'] },
	{ char: '🍌', name: '香蕉', keywords: ['香蕉', '水果'] },
	{ char: '🍉', name: '西瓜', keywords: ['西瓜', '水果', '夏'] },
	{ char: '🍇', name: '葡萄', keywords: ['葡萄', '水果'] },
	{ char: '🍓', name: '草莓', keywords: ['草莓', '水果'] },
	{ char: '🫐', name: '蓝莓', keywords: ['蓝莓', '水果'] },
	{ char: '🍈', name: '哈密瓜', keywords: ['哈密瓜', '水果', '甜'] },
	{ char: '🍒', name: '樱桃', keywords: ['樱桃', '水果'] },
	{ char: '🍑', name: '桃子', keywords: ['桃子', '水果'] },
	{ char: '🥭', name: '芒果', keywords: ['芒果', '水果'] },
	{ char: '🍍', name: '菠萝', keywords: ['菠萝', '水果'] },
	{ char: '🥥', name: '椰子', keywords: ['椰子', '水果'] },
	{ char: '🥝', name: '猕猴桃', keywords: ['猕猴桃', '水果'] },
	{ char: '🍅', name: '番茄', keywords: ['番茄', '蔬菜', '红'] },
	{ char: '🍆', name: '茄子', keywords: ['茄子', '蔬菜', '紫'] },
	{ char: '🥑', name: '牛油果', keywords: ['牛油果', '水果'] },
	{ char: '🥦', name: '西兰花', keywords: ['西兰花', '蔬菜'] },
	{ char: '🥬', name: '青菜', keywords: ['青菜', '蔬菜'] },
	{ char: '🥒', name: '黄瓜', keywords: ['黄瓜', '蔬菜'] },
	{ char: '🌶️', name: '辣椒', keywords: ['辣椒', '辣'] },
	{ char: '🌽', name: '玉米', keywords: ['玉米', '粮食'] },
	{ char: '🥕', name: '胡萝卜', keywords: ['胡萝卜', '蔬菜'] },
	{ char: '🧄', name: '大蒜', keywords: ['大蒜', '调料'] },
	{ char: '🧅', name: '洋葱', keywords: ['洋葱', '调料'] },
	{ char: '🍄', name: '蘑菇', keywords: ['蘑菇', '真菌'] },
	{ char: '🥜', name: '花生', keywords: ['花生', '坚果'] },
	{ char: '🍞', name: '面包', keywords: ['面包', '早餐'] },
	{ char: '🥐', name: '牛角包', keywords: ['面包', '牛角'] },
	{ char: '🥖', name: '法棍', keywords: ['面包', '法棍'] },
	{ char: '🥨', name: '椒盐卷饼', keywords: ['面包', '零食'] },
	{ char: '🧀', name: '芝士', keywords: ['芝士', '奶酪'] },
	{ char: '🥚', name: '鸡蛋', keywords: ['鸡蛋', '早餐'] },
	{ char: '🍳', name: '煎蛋', keywords: ['鸡蛋', '早餐', '煎'] },
	{ char: '🧈', name: '黄油', keywords: ['黄油', '牛奶'] },
	{ char: '🥞', name: '煎饼', keywords: ['煎饼', '早餐'] },
	{ char: '🧇', name: '华夫饼', keywords: ['华夫饼', '甜点'] },
	{ char: '🥓', name: '培根', keywords: ['培根', '肉'] },
	{ char: '🥩', name: '肉排', keywords: ['肉', '排'] },
	{ char: '🍗', name: '鸡腿', keywords: ['鸡', '肉'] },
	{ char: '🍖', name: '排骨', keywords: ['排骨', '肉'] },
	{ char: '🌭', name: '热狗', keywords: ['热狗', '快餐'] },
	{ char: '🍔', name: '汉堡', keywords: ['汉堡', '快餐'] },
	{ char: '🍟', name: '薯条', keywords: ['薯条', '快餐'] },
	{ char: '🍕', name: '披萨', keywords: ['披萨', '意大利'] },
	{ char: '🥪', name: '三明治', keywords: ['三明治', '快餐'] },
	{ char: '🥙', name: '沙瓦尔玛', keywords: ['沙瓦尔玛', '中东'] },
	{ char: '🌮', name: '墨西哥卷', keywords: ['墨西哥卷', '墨西哥'] },
	{ char: '🌯', name: '卷饼', keywords: ['卷饼', '墨西哥'] },
	{ char: '🥗', name: '沙拉', keywords: ['沙拉', '健康'] },
	{ char: '🥘', name: '浅锅', keywords: ['锅', '炒'] },
	{ char: '🥫', name: '罐头', keywords: ['罐头', '食品'] },
	{ char: '🍝', name: '意大利面', keywords: ['意大利面', '意大利'] },
	{ char: '🍜', name: '拉面', keywords: ['拉面', '面条', '日'] },
	{ char: '🍲', name: '火锅', keywords: ['火锅', '中餐'] },
	{ char: '🍥', name: '鱼饼', keywords: ['鱼饼', '日'] },
	{ char: '🍣', name: '寿司', keywords: ['寿司', '日'] },
	{ char: '🍱', name: '便当', keywords: ['便当', '日'] },
	{ char: '🥟', name: '饺子', keywords: ['饺子', '中餐'] },
	{ char: '🥠', name: ' fortune', keywords: [' fortune', '中餐'] },
	{ char: '🥮', name: '月饼', keywords: ['月饼', '中秋'] },
	{ char: '🍢', name: '关东煮', keywords: ['关东煮', '日'] },
	{ char: '🍡', name: '团子', keywords: ['团子', '日'] },
	{ char: '🍧', name: '刨冰', keywords: ['刨冰', '冰', '夏'] },
	{ char: '🍨', name: '冰淇淋', keywords: ['冰淇淋', '甜'] },
	{ char: '🍦', name: '冰淇淋', keywords: ['冰淇淋', '甜'] },
	{ char: '🥧', name: '派', keywords: ['派', '甜'] },
	{ char: '🧁', name: '纸杯蛋糕', keywords: ['蛋糕', '甜'] },
	{ char: '🍰', name: '蛋糕', keywords: ['蛋糕', '甜', '生日'] },
	{ char: '🎂', name: '生日蛋糕', keywords: ['蛋糕', '生日'] },
	{ char: '🍮', name: '布丁', keywords: ['布丁', '甜'] },
	{ char: '🍭', name: '棒棒糖', keywords: ['糖果', '甜'] },
	{ char: '🍬', name: '糖果', keywords: ['糖果', '甜'] },
	{ char: '🍫', name: '巧克力', keywords: ['巧克力', '甜'] },
	{ char: '🍿', name: '爆米花', keywords: ['爆米花', '零食'] },
	{ char: '🍩', name: '甜甜圈', keywords: ['甜甜圈', '甜'] },
	{ char: '🍪', name: '饼干', keywords: ['饼干', '甜'] },
	{ char: '☕', name: '咖啡', keywords: ['咖啡', '饮料'] },
	{ char: '🍵', name: '茶', keywords: ['茶', '饮料'] },
	{ char: '🧃', name: '果汁盒', keywords: ['果汁', '饮料'] },
	{ char: '🥤', name: '饮料', keywords: ['饮料', '汽水'] },
	{ char: '🧋', name: '奶茶', keywords: ['奶茶', '饮料'] },
	{ char: '🍶', name: '清酒', keywords: ['酒', '日'] },
	{ char: '🍺', name: '啤酒', keywords: ['啤酒', '酒'] },
	{ char: '🍻', name: '碰杯', keywords: ['啤酒', '干杯'] },
	{ char: '🥂', name: '香槟', keywords: ['香槟', '酒', '庆祝'] },
	{ char: '🍷', name: '红酒', keywords: ['红酒', '酒'] },
	{ char: '🥃', name: '威士忌', keywords: ['威士忌', '酒'] },
	{ char: '🍸', name: '鸡尾酒', keywords: ['鸡尾酒', '酒'] },
	{ char: '🍹', name: '果汁酒', keywords: ['果汁酒', '酒'] },
	{ char: '🧊', name: '冰块', keywords: ['冰', '冷'] },
	{ char: '🥄', name: '勺子', keywords: ['勺子', '餐具'] },
	{ char: '🍴', name: '叉子', keywords: ['叉子', '餐具'] },
	{ char: '🍽️', name: '餐具', keywords: ['餐具', '吃饭'] },
	{ char: '🥣', name: '杯子', keywords: ['杯子', '碗'] },
	{ char: '🥢', name: '筷子', keywords: ['筷子', '中餐'] }
];
