export const smileysData = [
	{ char: '😀', name: '笑脸', keywords: ['笑', '开心', 'happy'] },
	{ char: '😃', name: '大笑', keywords: ['开心', '快乐'] },
	{ char: '😄', name: '微笑', keywords: ['笑', '开心'] },
	{ char: '😁', name: '偷笑', keywords: ['笑', '开心'] },
	{ char: '😆', name: '笑哭', keywords: ['笑', '哭', '大笑'] },
	{ char: '😅', name: '冷汗', keywords: ['汗', '尴尬'] },
	{ char: '😂', name: '笑哭', keywords: ['笑', '哭'] },
	{ char: '🤣', name: '大笑', keywords: ['笑', '搞笑'] },
	{ char: '😊', name: '微笑', keywords: ['笑', '开心', '脸红'] },
	{ char: '😇', name: '天使', keywords: ['天使', '乖'] },
	{ char: '🙂', name: '微笑', keywords: ['微笑'] },
	{ char: '🙃', name: '倒脸', keywords: ['倒', '调皮'] },
	{ char: '😉', name: '眨眼', keywords: ['眨眼', '调皮'] },
	{ char: '😌', name: '安心', keywords: ['安心', '放松'] },
	{ char: '😍', name: '花痴', keywords: ['爱', '喜欢', '心'] },
	{ char: '🥰', name: '爱心', keywords: ['爱', '喜欢'] },
	{ char: '😘', name: '飞吻', keywords: ['吻', '爱'] },
	{ char: '😜', name: '调皮', keywords: ['调皮', '眨眼'] },
	{ char: '😝', name: '得意', keywords: ['得意', '调皮'] },
	{ char: '😛', name: '吐舌', keywords: ['吐舌', '调皮'] },
	{ char: '🤑', name: '钱', keywords: ['钱', '发财'] },
	{ char: '🤗', name: '拥抱', keywords: ['拥抱', '抱抱'] },
	{ char: '🤔', name: '思考', keywords: ['思考', '想'] },
	{ char: '🤐', name: '闭嘴', keywords: ['闭嘴', '安静'] },
	{ char: '😐', name: '面无表情', keywords: ['平淡', '无表情'] },
	{ char: '😑', name: '无表情', keywords: ['无表情'] },
	{ char: '😶', name: '闭嘴', keywords: ['闭嘴', '无语'] },
	{ char: '😏', name: '得意', keywords: ['得意', '坏笑'] },
	{ char: '😒', name: '无奈', keywords: ['无奈', '无语'] },
	{ char: '🙄', name: '白眼', keywords: ['白眼', '无奈'] },
	{ char: '😬', name: '鬼脸', keywords: ['鬼脸', '尴尬'] },
	{ char: '🤥', name: '说谎', keywords: ['说谎', '皮诺曹'] },
	{ char: '😔', name: '失落', keywords: ['失落', '难过'] },
	{ char: '😷', name: '生病', keywords: ['生病', '感冒'] },
	{ char: '🤒', name: '发烧', keywords: ['发烧', '生病'] },
	{ char: '🤕', name: '受伤', keywords: ['受伤', '头疼'] },
	{ char: '🤢', name: '恶心', keywords: ['恶心', '吐'] },
	{ char: '🤮', name: '吐', keywords: ['吐', '恶心'] },
	{ char: '🤧', name: '喷嚏', keywords: ['喷嚏', '感冒'] },
	{ char: '🥵', name: '热', keywords: ['热', '中暑'] },
	{ char: '🥶', name: '冷', keywords: ['冷', '寒冷'] },
	{ char: '🥴', name: '晕', keywords: ['晕', '醉了'] },
	{ char: '😵', name: '晕', keywords: ['晕', '头晕'] },
	{ char: '🤯', name: '爆炸', keywords: ['爆炸', '头脑'] },
	{ char: '🤠', name: '牛仔', keywords: ['牛仔', '帽子'] },
	{ char: '🥳', name: '派对', keywords: ['派对', '庆祝'] },
	{ char: '🥺', name: '求', keywords: ['求', '可怜'] },
	{ char: '😎', name: '墨镜', keywords: ['酷', '墨镜'] },
	{ char: '🤓', name: '学霸', keywords: ['学霸', '书呆'] }
];
